### PR TITLE
Add workflow to build a bin artifact if full.yaml changes

### PR DESCRIPTION
**Pull request by Columbo**
If the full.yaml file is changed in dev or main branch a new workflow to build an artifact via GitHub actions will be started.
This PR does not affect the development of this project in any kind. It allows the usage of a workflow like this which could later be extended to add the bin directly as a release or to replace the currently published bin file. 
At the moment, it will just create a zip file which contains the bin file as an artifact which can be downloaded if needed. 

The build procedure consists of multiple steps.

1. Validate
Check if all environment variables are set. 
Four variables need to be set in the GitHub Repository under Settings->General->Security->Secrets and variables->Actions->Repository secrets:
API_ENCRYPTION_KEY (base64, 32bit long) 
OTA_PASSWORD 
WIFI_SSID
WIFI_PASSWORD
An Error message will occur if the validation fails and the workflow stops.
2. Checkout Code in workflow environment
3. Setup Python in workflow environment
4. Set Environment variable for the whole workflow. These variables can be used in all following steps.
5. Install esphome in workflow environment
6. Compile Binary
7. Upload artifact, a zip file which contains the binary file

### CODE REVIEW

**Comment by wrfz** [comment]
> If the full.yaml file is changed in dev or main branch a new workflow to build an artifact via GitHub actions will be started.

It does not necessarily have to change full.yaml. This only happens when new sensors are added or existing ones are renamed. Workflow should also be executed if the component changes here:
https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN/tree/main/components/daikin_rotex_can

**Comment by Columbo** [comment]
so any change in the directory "daikin_rotex_can" should trigger the workflow?

**Comment by wrfz** [comment]
yes

**Comment by Columbo** [comment]
ok, i will ad this additional requirement tomorrow to this PR

**Comment by Columbo** [comment]
The workflow should now be triggered by changes of the full.yaml and by component changes.
I added an additional path in the build config:
-  "build.yml->on:->push:->paths:" by adding the path "components/**"

** references all files and subdirectories underneath the directory "components" regardless of the depth of the hierarchy

**Comment by wrfz** [comment]
Is this examples/secrets.yaml necessary for the workflow?
build.yaml accesses secrets. Is this file filled with the values by Github from the secrets area?
What does !env_var mean ?
examples/ - folder is meant for the users. Do the users need these !env_var entries? Or is this only for Github? I want to avoid side effects for local users.

**Pull request merged**
